# Generated by Django 2.1.3 on 2018-11-27 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('content', models.TextField(null=True, verbose_name='content')),
                ('status', models.CharField(choices=[('UNREVIEWED', 'Unreviewed'), ('REVIEWED', 'Reviewed')], max_length=16, verbose_name='status')),
                ('created', models.DateField(auto_now_add=True, verbose_name='created')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
        ),
    ]
